# Tezio Signer Configuration

# security: remote_ip_check - only allow requests from IPs listed in allowed_ips below
#           auth_check - only accept requests that include a signature that auth_key must validate

security:
    remote_ip_check: True
    auth_check: True

verbose: False # Print URL and any data received with request and high water mark data

allowed_ips: 
    ["127.0.0.1"]
